name: {{ ProjectName }}
services:
  jumpbox:
    build:
      context: .
      dockerfile: ../Dockerfile
    profiles:
      - all
      - jumpbox
    volumes:
      - ~/.aws:/home/jarvis/.aws:ro
      - ../local/.zsh_history:/home/jarvis/.zsh_history
      -  ../:/home/jarvis/apps
    command: sleep infinity