name: Auto Tag and Release

on:
  push:
    branches:
      - master

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Check if commit message has 'release:' keyword
        id: check_release
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"release:"* ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if not a release commit
        if: steps.check_release.outputs.is_release == 'false'
        run: exit 0

      - name: Determine next tag
        condition: steps.check_release.outputs.is_release == 'true'
        id: newtag
        run: |
          latest=$(git tag --list 'v*' --sort=-v:refname | head -n 1)
          if [ -z "$latest" ]; then
            echo "new_tag=v0.0.1" >> $GITHUB_OUTPUT
          else
            IFS='.' read -r major minor patch <<< "${latest#v}"
            patch=$((patch + 1))
            echo "new_tag=v${major}.${minor}.${patch}" >> $GITHUB_OUTPUT
          fi

      - name: Push new tag using PAT
        condition: steps.check_release.outputs.is_release == 'true'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git tag ${{ steps.newtag.outputs.new_tag }}
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin ${{ steps.newtag.outputs.new_tag }}

      - name: Create GitHub Release
        condition: steps.check_release.outputs.is_release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.newtag.outputs.new_tag }}
          generate_release_notes: true
