name: Auto Deploy with Release Tag

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag and increment
        id: newtag
        run: |
          latest_tag=$(git tag --list 'v*' --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            new_tag="v0.0.1"
          else
            IFS='.' read -r major minor patch <<< "${latest_tag#v}"
            patch=$((patch+1))
            new_tag="v${major}.${minor}.${patch}"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Tag and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.newtag.outputs.new_tag }}
          git push origin ${{ steps.newtag.outputs.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.newtag.outputs.new_tag }}
          generate_release_notes: true
